[tools]
# Programming Languages
python = "latest"
java = ["17", "21"]
go = "latest"
gleam = "latest"
node = "latest"

# IaC
terraform = ["1.9.5"]

# Cargo Plugins
"cargo:bp" = "latest"
"cargo:loco-cli" = "latest"
"cargo:cargo-wizard" = "latest"
"cargo:cargo-make" = "latest"
"cargo:cargo-machete" = "latest"
"cargo:cargo-sort" = "latest"
"cargo:cargo-features-manager" = "latest"
"cargo:cargo-chef" = "latest"
"cargo:bacon-ls" = "latest"

# npm Packages
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"

[settings]
legacy_version_file_disable_tools = ["terraform"]
experimental = true
